# Visit https://docs.github.com/en/actions for more information about using
# GitHub Actions and learn how-to build custom automated CI/CD workflows

# Visit https://cli.github.com/manual/gh_release_create for more information
# about using and how-to create GitHub repository releases with CLI tools

name: "Pre-release"
run-name: "Pre-release ${{ github.ref_name }} by @${{ github.actor }}"
on:
  push:
    tags:
      - '!v[0-9]+.[0-9]+.[0-9]+'
      - '!v20[0-9][0-9][0-1][0-9][0-3][0-9]'
      - 'alpha/v[0-9]+.[0-9]+.[0-9]+**'
      - 'alpha/v20[0-9][0-9][0-1][0-9][0-3][0-9]**'
      - 'beta/v[0-9]+.[0-9]+.[0-9]+**'
      - 'beta/v20[0-9][0-9][0-1][0-9][0-3][0-9]**'
      - 'devel/v[0-9]+.[0-9]+.[0-9]+**'
      - 'devel/v20[0-9][0-9][0-1][0-9][0-3][0-9]**'
      - 'test/v[0-9]+.[0-9]+.[0-9]+**'
      - 'test/v20[0-9][0-9][0-1][0-9][0-3][0-9]**'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha*'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta*'
      - 'v[0-9]+.[0-9]+.[0-9]+-devel*'
      - 'v[0-9]+.[0-9]+.[0-9]+-test*'
      - 'v20[0-9][0-9][0-1][0-9][0-3][0-9]-alpha*'
      - 'v20[0-9][0-9][0-1][0-9][0-3][0-9]-beta*'
      - 'v20[0-9][0-9][0-1][0-9][0-3][0-9]-devel*'
      - 'v20[0-9][0-9][0-1][0-9][0-3][0-9]-test*'

permissions:
  contents: write  # Required to use GitHub Workflow actions
  id-token: write  # Required to request an OpenID Connect token

env:
  GITHUB_TOKEN: "${{ secrets.github_token }}"
  RUNNER_ARCH: "amd64, arm64, armhf, ppc64le, riscv64, s390x"
  RUNNER_OS: "macOS-latest, ubuntu-latest, windows-latest"

jobs:
  create:
    name: "Create Pre-release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v7

      - name: "Setup environment"
        id: setup-environment
        run: |
          echo "OWNER_NAME=$(tr '[:upper:]' '[:lower:]' <<< $GITHUB_REPOSITORY | cut -d'/' -f1 | tr '_' '-')" >> "$GITHUB_ENV"
          echo "REPO_NAME=$(tr '[:upper:]' '[:lower:]' <<< $GITHUB_REPOSITORY | cut -d'/' -f2 | tr '_' '-')" >> "$GITHUB_ENV"

      - name: "GitHub release"
        id: github-release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release create \
            "${{ github.ref_name }}" \
            --generate-notes \
            --latest=false --prerelease \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            --verify-tag
            # "${{ runner.temp }}/artifact.tar.gz" \
            # "${{ runner.temp }}/artifact.zip"
